### PR TITLE
fix: handle getFile returning null and close #106

### LINKED ISSUE #106: [BUG] the version 1.2 introduced a regression
**Describe the bug**

When running the new version of `react-dropzone: @14.3.5` [link](https://github.com/react-dropzone/react-dropzone/releases/tag/v14.3.5), I noticed a regression introduced in this library

🐛 This bug was introduced in this [commit](https://github.com/react-dropzone/file-selector/commit/11d34a75f1dfa668e3da8c62911ce7aead224619#diff-b1b6505efe0d05e629847160e4e4c7ca59d9828ea5023fad78632e0a325debd7R127)

The actual error is `FileDrop-ky6DIxvn.js:5`
```
TypeError: Cannot read properties of undefined (reading 'getFile')
    at FileDrop-ky6DIxvn.js:1:43484
    at Generator.next (<anonymous>)
    at FileDrop-ky6DIxvn.js:1:386
    at new Promise (<anonymous>)
    at E (FileDrop-ky6DIxvn.js:1:183)
    at FileDrop-ky6DIxvn.js:1:43435
    at async Promise.all (__/index 0)
```

Accordingly to the experimental documentation of **DataTransferItem: getAsFileSystemHandle() method** [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle)
> A [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).
If the item's [kind](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/kind) property is "file", and this item is accessed in the [dragstart](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragstart_event) or [drop](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event) event handlers, then the returned promise is fulfilled with a [FileSystemFileHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle) if the dragged item is a file or a [FileSystemDirectoryHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle) if the dragged item is a directory.
**Otherwise, the promise fulfills with null.**

The return value can be a promise or `null`, but the current code doesn't manage `null` values

**Expected behavior**
This shouldn't crash at runtime 

**Desktop (please complete the following information):**
- userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Additional context**

**It seems that the old/legacy behavior is working as expected.**

### PR DESCRIPTION
**Pull request by rolandjitsu**
**What kind of change does this PR introduce?**
- [x] Bug Fix
- [ ] Feature
- [ ] Refactoring
- [ ] Style
- [ ] Build
- [ ] Chore
- [ ] Documentation
- [ ] CI

**Did you add tests for your changes?**
- [x] Yes, my code is well tested
- [ ] Not relevant

**If relevant, did you update the documentation?**
- [ ] Yes, I've updated the documentation
- [x] Not relevant

**Summary**

Address https://github.com/react-dropzone/file-selector/issues/106.

**Does this PR introduce a breaking change?**

No.

**Other information**

### CODE REVIEW

File: src/file-selector.ts [hunk 1]
```diff
@@ -125,18 +125,25 @@ function fromDataTransferItem(item: DataTransferItem, entry?: FileSystemEntry |
         return (item as any).getAsFileSystemHandle()
             .then(async (h: any) => {
                 const file = await h.getFile();
```
Comment (buenjybar) [inline src/file-selector.ts:127]: I think the issue in that case is `h` is undefined, so it will crash on the this line 127.

Comment (rolandjitsu) [reply src/file-selector.ts:127]: True. That's the one that can be `null`.

Comment (rolandjitsu) [reply src/file-selector.ts:127]: > If the item's [kind](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/kind) property is "file", and this item is accessed in the [dragstart](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dragstart_event) or [drop](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event) event handlers, then the returned promise is fulfilled with a [FileSystemFileHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle) if the dragged item is a file or a [FileSystemDirectoryHandle](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle) if the dragged item is a directory.
>
> Otherwise, the promise fulfills with null.

Essentially, `h` can be null. The return value of `getAsFileSystemHandle` should always be a promise.

File: src/file-selector.ts [hunk 2]
```diff
@@ -124,19 +124,26 @@ function fromDataTransferItem(item: DataTransferItem, entry?: FileSystemEntry |
...
                 return toFileWithPath(file);
             });
     }
     const file = item.getAsFile();
     if (!file) {
-        return Promise.reject(`${item} is not a File`);
+        return notAFile(item);
     }
     const fwp = toFileWithPath(file, entry?.fullPath ?? undefined);
     return Promise.resolve(fwp);
```
Comment (buenjybar) [inline src/file-selector.ts:140]: It seem's that now the code will throw and exit with `not a file` and won't actually read the file when there is actually a valid file using the `item.getAsFile()` code below.

Do you know what was the initial benefit of using this experimental `getAsFileSystemHandle` function ?
Can we simply drop it ?

It would be great to fallback to the original code

Comment (jonkoops) [reply src/file-selector.ts:140]: Agreed, this should be a fallback, not an exit case. We should also be adding some types here to ensure correctness.

**Comment by jonkoops** [comment]
I tried to refactor the logic as much as possible without touching any of the parameters or side-effects passed into `toFileWithPath()`. I also added some type definitions for `getAsFileSystemHandle()`, which is not yet included in TypeScript due to the experimental nature of the API.

This is what I came up with:
```ts
async function fromDataTransferItem(item: DataTransferItem, entry?: FileSystemEntry | null) {
    const handle = await item.getAsFileSystemHandle?.();

    if (handle && isFileHandler(handle)) {
        const file = await handle.getFile();
        file.handle = handle;
        return toFileWithPath(file);
    }

    const file = item.getAsFile();

    if (!file) {
        throw new Error(`${item} is not a File`);
    }

    return toFileWithPath(file, entry?.fullPath ?? undefined);
}

function isFileHandler(handle: FileSystemFileHandle | FileSystemDirectoryHandle): handle is FileSystemFileHandle {
    return handle.kind === 'file';
}

declare global {
    interface DataTransferItem {
        // This method is not yet widely supported in all browsers, and is thus marked as optional.
        // See: https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle
        getAsFileSystemHandle?(): Promise<FileSystemFileHandle | FileSystemDirectoryHandle | null>;
    }
}
```

WDYT?

**Comment by buenjybar** [comment]
> WDYT?

This sounds lovely

File: src/file-selector.ts (hunk 2 above)
Comment (rolandjitsu) [reply src/file-selector.ts:140]: @buenjybar could you share more about how you get into that situation? Because if `getAsFileSystemHandle` exists and you're actually dropping a file, it should work in theory.

Comment (jonkoops) [reply src/file-selector.ts:140]: Good point, that should work actually. The only time it would not is if you drop a directory I guess? But then also `.getAsFile()` would also not work I imagine.

**Comment by rolandjitsu** [comment]
@jonkoops thanks, but as far as I can see/remember, `fromDataTransferItem` is called from `toFilePromises` only, which is called here:
```js
async function getDataTransferFiles(dt: DataTransfer, type: string) {
    // IE11 does not support dataTransfer.items
    // See https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/items#Browser_compatibility
    if (dt.items) {
        const items = fromList<DataTransferItem>(dt.items)
            .filter(item => item.kind === 'file');
        // According to https://html.spec.whatwg.org/multipage/dnd.html#dndevents,
        // only 'dragstart' and 'drop' has access to the data (source node)
        if (type !== 'drop') {
            return items;
        }
        const files = await Promise.all(items.map(toFilePromises));
```
so in practice, items that are not files should not make it through.

So it makes me wonder what else is going on there.

**Comment by rolandjitsu** [comment]
> Got it yeah, I was going off a specific section of code without understanding the whole program fully, which seems to have guided me on some assumptions that were more defensive than required. In general I tend to use the types as guidance and do defensive programming where there is a possibility of a gap between the type and implementation.
> 
> I'll do some testing on Firefox to see if I can reproduce this issue.

No worries. I appreciate all the help! That sounds good, but I still think that if @buenjybar would provide more context, it would be very helpful.

**Comment by buenjybar** [comment]
> > Got it yeah, I was going off a specific section of code without understanding the whole program fully, which seems to have guided me on some assumptions that were more defensive than required. In general I tend to use the types as guidance and do defensive programming where there is a possibility of a gap between the type and implementation.
> > I'll do some testing on Firefox to see if I can reproduce this issue.
> 
> No worries. I appreciate all the help! That sounds good, but I still think that if @buenjybar would provide more context, it would be very helpful.

here https://github.com/react-dropzone/file-selector/pull/108

**Comment by rolandjitsu** [comment]
> > > Got it yeah, I was going off a specific section of code without understanding the whole program fully, which seems to have guided me on some assumptions that were more defensive than required. In general I tend to use the types as guidance and do defensive programming where there is a possibility of a gap between the type and implementation.
> > > I'll do some testing on Firefox to see if I can reproduce this issue.
> > 
> > 
> > No worries. I appreciate all the help! That sounds good, but I still think that if @buenjybar would provide more context, it would be very helpful.
> 
> here #108
> 
> this is the full project setup that is reproducing a production bug https://github.com/buenjybar/react-dropzone-issue106/tree/master/my-app

Thanks for taking the time to provide a reproducible example. We'll look into it.

File: src/file-selector.ts (hunk 2 above)
Comment (rolandjitsu) [reply src/file-selector.ts:140]: Should we go ahead with this change? As far as [getAsFileSystemHandle](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle) goes, we're doing the right thing, guarding for `null`.

Alternatively, we could make it go to L135 (on the right).

Comment (rolandjitsu) [reply src/file-selector.ts]: Right now, when the handle is undefined/null, we reject with `not a file`. I'm not sure if that's what we want and how we even get there since we filter for files way before the function is called. I wasn't able to replicate outside cypress, but I would like to understand how it happens.

Alternatively, we could make the code path go to `getAsFile` when the handle is undefined/null?

**Comment by jonkoops** [comment]
You want to do the fallback solution I proposed instead? It would cover all the cases, but it is hard to tell if it would actually resolve the problem. I would agree with your earlier assessment that if `getAsFileSystemHandle()` doens't return something, then `getFile()` likely would not either, but it seems a more fragile API than expected.

**Comment by MathiasWP** [comment]
> > LGTM, let's get this landed.
> 
> I wonder if we should reject or go to `getAsFile`? @MathiasWP do you know how you ended up with your issue?

Not sure how it was triggered, we tried investigating but couldn't find anything. 

IMO it makes sense to fallback to `getAsFile`, given that the is still [marked as experimental](https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/getAsFileSystemHandle). Could be a browser bug.

**Comment by rolandjitsu** [comment]
Ok. It sounds like the sensible thing todo is to go for a fallback. Let me add that.

**Comment by rolandjitsu** [comment]
Btw, I've added support for returning a custom error in that case where either we have `null` or `getAsFile` also returns `null`. It's in https://github.com/react-dropzone/file-selector/tree/feat/custom-err. If it makes sense, I can create a new PR or add it to this PR.

**Comment by jonkoops** [comment]
@rolandjitsu could you give this one a rebase with `master`?

File: src/file-selector.ts [hunk 3]
```diff
@@ -120,27 +120,32 @@ function flatten<T>(items: any[]): T[] {
...
+        if (h === null) {
+            throw new Error(`${item} is not a File`);
+        }
+        // It seems that the handle can be `undefined` (see https://github.com/react-dropzone/file-selector/issues/120),
+        // so we check if it isn't; if it is, the code path continues to the next API (`getAsFile`).
+        if (h !== undefined) {
+            const file = await h.getFile();
+            file.handle = h;
+            return toFileWithPath(file);
+        }
```
Comment (MathiasWP) [inline src/file-selector.ts:141]: Wouldn't this be a safer fallback? Isn't it nice to try `getFile` if `getAsFileSystemHandle` does not return the expected data for some other unknown reason? 

```suggestion
        const h = await (item as any).getAsFileSystemHandle();
        if(!h) {
	        const file = await h.getFile();
	        if(!file) {
	        	throw new Error(`${item} is not a File`);
	        }
            file.handle = h;
            return toFileWithPath(file);
        }
```

And then you can skip the 
```ts
	const file = item.getAsFile(); 
    if (!file) {
        throw new Error(`${item} is not a File`);
    }
```

below, because it will always try `getFile`?

Comment (rolandjitsu) [reply src/file-selector.ts:141]:
```
if(!h) {
	        const file = await h.getFile();
```

That will essentially throw an exception because it will evaluate if `h` is `undefined` or `null`. We want the opposite of that. Note that `getFile` and `getAsFile` are 2 different APIs that exist on different objects.

**Comment by rolandjitsu** [comment]
> @rolandjitsu could you give this one a rebase with master?

It should already be rebased.
